name: Detect Changes for Apps
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
    - 'apps/**'
    - 'packages/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      apps-to-build: ${{ steps.changes.outputs.apps }}
      matrix: ${{ steps.changes.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install

    - name: Detect changes using Turbo
      id: changes
      run: |
        # Get changed files
        CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
        echo "Changed files found: $(echo "$CHANGED_FILES" | wc -l)"

        # Use Turbo to find affected packages for each app
        APPS_TO_BUILD=()

        # Get all apps from workspace - try multiple approaches
        echo "Getting apps from workspace..."

        # Method 1: Try turbo list
        APPS=""
        echo "Attempting to use Turbo list..."
        if bun run turbo list --filter="apps/*" > /tmp/turbo_output 2>&1; then
          APPS=$(cat /tmp/turbo_output | grep "^@tuturuuu/" | tr -d ' ')
          echo "✅ Turbo list successful, found apps: $APPS"
        else
          echo "⚠️  Turbo list failed (likely due to Tailwind CSS v4 WASM dependencies)"
          echo "Turbo error output:"
          cat /tmp/turbo_output | head -10
          echo "..."
          
          echo "🔄 Falling back to directory scanning method..."
          # Method 2: Direct directory scanning
          APPS=$(find apps/*/package.json -exec sh -c 'grep -l "name.*@tuturuuu" {} | sed "s|apps/\([^/]*\)/package.json|@tuturuuu/\1|"' \;)
          echo "✅ Directory scan successful, found apps: $APPS"
        fi

        # Fallback: hardcode known apps if all else fails
        if [ -z "$APPS" ]; then
          echo "Using fallback app list..."
          APPS="@tuturuuu/nova @tuturuuu/web @tuturuuu/calendar @tuturuuu/rewise @tuturuuu/shortener @tuturuuu/tumeet @tuturuuu/finance @tuturuuu/external @tuturuuu/playground"
        fi

        for app in $APPS; do
          # Check if app directory changed
          # Extract the app name without the @tuturuuu/ prefix
          app_name=${app#@tuturuuu/}
          app_path="apps/$app_name"
          if echo "$CHANGED_FILES" | grep -q "^$app_path/"; then
            APPS_TO_BUILD+=("$app")
            continue
          fi
          
          # Try to use Turbo to find dependencies, fallback to package.json scanning
          AFFECTED=""
          if bun run turbo run build --filter="$app" --dry-run > /tmp/turbo_build_output 2>&1; then
            AFFECTED=$(cat /tmp/turbo_build_output | grep "^@tuturuuu/" | tr -d ' ')
            echo "Turbo build analysis for $app successful, found: $AFFECTED"
          else
            echo "Turbo build analysis for $app failed, using package.json fallback..."
            # Fallback: read dependencies directly from package.json
            if [ -f "apps/$app_name/package.json" ]; then
              AFFECTED=$(grep -o '"@tuturuuu/[^"]*"' "apps/$app_name/package.json" | tr -d '"')
              echo "Package.json fallback for $app found: $AFFECTED"
            fi
          fi
          
          # Check if any of the affected packages changed
          for pkg in $AFFECTED; do
            pkg_path=""
            if [[ $pkg == @tuturuuu/* ]]; then
              pkg_name=${pkg#@tuturuuu/}
              pkg_path="packages/$pkg_name"
            elif [[ $pkg == apps/* ]]; then
              pkg_name=${pkg#apps/}
              pkg_path="apps/$pkg_name"
            fi
            
            if [ -n "$pkg_path" ] && echo "$CHANGED_FILES" | grep -q "^$pkg_path/"; then
              APPS_TO_BUILD+=("$app")
              break
            fi
          done
        done

        # Remove duplicates and create matrix
        UNIQUE_APPS=$(printf '%s\n' "${APPS_TO_BUILD[@]}" | sort -u | grep -v '^$')
        MATRIX=$(echo "$UNIQUE_APPS" | jq -R -s -c 'split("\n")[:-1] | map({app: .})')

        echo "apps=$(echo "$UNIQUE_APPS" | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_OUTPUT
        echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

        echo "=== Debug Information ==="
        echo "Changed files:"
        echo "$CHANGED_FILES" | head -20
        echo "..."
        echo ""
        echo "All apps found:"
        echo "$APPS"
        echo ""
        echo "Apps to build: $UNIQUE_APPS"
        echo "Matrix: $MATRIX"
