name: Supabase Staging Migration

on:
  workflow_run:
    workflows: ["Vercel Platform Preview Deployment"]
    types:
      - completed
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    name: Migrate staging database
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # Only run if the Vercel deployment succeeded or if manually triggered
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      STAGING_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}
      STAGING_DB_URL: ${{ secrets.STAGING_DB_URL }}
    steps:
      - uses: actions/checkout@v5
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy migrations to staging
        run: |
          cd apps/db
          supabase link --project-ref ${{ env.STAGING_PROJECT_ID }}
          supabase db push
