name: Test

on:
  push:
    branches: ["main"]
    paths:
      - 'apps/**/src/**'
      - 'packages/**/src/**'
      - '**/*.test.{ts,tsx}'
      - '**/package.json'
      - 'bun.lockb'
      - 'turbo.json'
      - '**/tsconfig*.json'
      - '.github/workflows/turbo-unit-tests.yaml'
  pull_request:
    paths:
      - 'apps/**/src/**'
      - 'packages/**/src/**'
      - '**/*.test.{ts,tsx}'
      - '**/package.json'
      - 'bun.lockb'
      - 'turbo.json'
      - '**/tsconfig*.json'
      - '.github/workflows/turbo-unit-tests.yaml'

jobs:
  build:
    name: Unit Tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]

    env:
      # Use Vercel Remote Caching
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

      # Configure production Supabase client
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.PRODUCTION_SUPABASE_PUBLISHABLE_KEY }}
      SUPABASE_SECRET_KEY: ${{ secrets.PRODUCTION_SUPABASE_SECRET_KEY }}

      # Configure infrastructure
      PROXY_API_KEY: ${{ secrets.PROXY_API_KEY }}
      NEXT_PUBLIC_PROXY_API_KEY: ${{ secrets.NEXT_PUBLIC_PROXY_API_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Check for test-relevant changes
        id: test_check
        run: |
          BASE_COMMIT=$(git rev-parse --verify HEAD~ 2>/dev/null || echo "$GITHUB_SHA")
          changed=$(git diff --name-only "$BASE_COMMIT" HEAD | grep -E 'apps/.*/src/|packages/.*/src/|\.test\.(ts|tsx)|package\.json|bun\.lockb|turbo\.json|tsconfig.*\.json|\.github/workflows/turbo-unit-tests\.yaml' | wc -l)
          if [ "$changed" -eq 0 ]; then
            echo "No test-relevant changes detected. Skipping tests."
            echo "skip_tests=true" >> $GITHUB_OUTPUT
          else
            echo "Test-relevant changes detected in $changed files."
            echo "skip_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Cache turbo build setup
        if: steps.test_check.outputs.skip_tests != 'true'
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Cache dependencies
        if: steps.test_check.outputs.skip_tests != 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Setup bun
        if: steps.test_check.outputs.skip_tests != 'true'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.1"

      - name: Use Node.js 24
        if: steps.test_check.outputs.skip_tests != 'true'
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        if: steps.test_check.outputs.skip_tests != 'true'
        run: bun install --frozen-lockfile

      - name: Build workspace dependencies
        if: steps.test_check.outputs.skip_tests != 'true'
        run: bunx turbo run build --filter='@tuturuuu/types'

      - name: Test
        if: steps.test_check.outputs.skip_tests != 'true'
        run: bun run test
