name: Vercel Rewise Preview Deployment
on:
  workflow_run:
    workflows: [ "Detect Changes for Apps" ]
    types: [ completed ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment regardless of changes'
        required: false
        default: 'false'
        type: boolean

jobs:
  check-changes:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch != 'production' || github.event_name == 'workflow_dispatch'
    outputs:
      rewise_detected: ${{ steps.check-rewise.outputs.rewise_detected }}
      project_id: ${{ steps.extract-project-id.outputs.project_id }}
    steps:
    - name: Download apps-to-build artifact
      uses: actions/download-artifact@v4
      id: download-artifact
      continue-on-error: true
      with:
        name: apps-to-build
        path: ./
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Check if rewise should be built
      id: check-rewise
      run: |
        # Force deploy if triggered manually with force_deploy=true
        if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.force_deploy }}" = "true" ]; then
          echo "rewise_detected=true" >> $GITHUB_OUTPUT
          echo "✅ Force deployment requested via workflow_dispatch"
          exit 0
        fi
        
        # Check if artifact was downloaded successfully
        if [ "${{ steps.download-artifact.outcome }}" != "success" ]; then
          echo "rewise_detected=false" >> $GITHUB_OUTPUT
          echo "❌ Failed to download apps-to-build artifact, skipping build"
          exit 0
        fi
        
        if [ -f "apps-to-build.txt" ]; then
          if grep -q "rewise" "apps-to-build.txt"; then
            echo "rewise_detected=true" >> $GITHUB_OUTPUT
            echo "✅ Rewise changes detected, proceeding with build"
          else
            echo "rewise_detected=false" >> $GITHUB_OUTPUT
            echo "❌ No Rewise changes detected, skipping build"
          fi
        else
          echo "rewise_detected=false" >> $GITHUB_OUTPUT
          echo "❌ apps-to-build.txt not found, skipping build"
        fi

    - name: Extract project ID
      id: extract-project-id
      env:
        PROJECT_ID: ${{ secrets.VERCEL_REWISE_PROJECT_ID }}
      run: |
        echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT

  deploy-rewise:
    needs: check-changes
    if: needs.check-changes.outputs.rewise_detected == 'true'
    uses: ./.github/workflows/build-app.yml
    with:
      vercel-project-id: ${{ needs.check-changes.outputs.project_id  }}
    secrets: inherit
