name: Vercel Shortener Preview Deployment
on:
  workflow_run:
    workflows: ["Detect Changes for Apps"]
    types: [completed]
    branches-ignore: [main, production]

jobs:
  deploy-shortener:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      contains(fromJSON(github.event.workflow_run.outputs.apps), 'shortener')
    uses: ./.github/workflows/build-app.yml
    with:
      app: shortener
      app-path: apps/shortener
      build-command: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      vercel-project-id: ${{ secrets.VERCEL_SHORTENER_PROJECT_ID }}
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
