name: Vercel Rewise Preview Deployment
on:
  workflow_run:
    workflows: [ "Detect Changes for Apps" ]
    types: [ completed ]
    branches-ignore: [ production ]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      rewise_detected: ${{ steps.check-rewise.outputs.rewise_detected }}
      project_id: ${{ steps.extract-project-id.outputs.project_id }}
    steps:
    - name: Download apps-to-build artifact
      uses: actions/download-artifact@v4
      with:
        name: apps-to-build
        path: ./
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Check if rewise should be built
      id: check-rewise
      run: |
        if [ -f "apps-to-build.txt" ]; then
          if grep -q "rewise" "apps-to-build.txt"; then
            echo "rewise_detected=true" >> $GITHUB_OUTPUT
            echo "✅ Rewise changes detected, proceeding with build"
          else
            echo "rewise_detected=false" >> $GITHUB_OUTPUT
            echo "❌ No Rewise changes detected, skipping build"
          fi
        else
          echo "rewise_detected=false" >> $GITHUB_OUTPUT
          echo "❌ apps-to-build.txt not found, skipping build"
        fi

    - name: Extract project ID
      id: extract-project-id
      env:
        PROJECT_ID: ${{ secrets.VERCEL_REWISE_PROJECT_ID }}
      run: |
        echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT

  deploy-rewise:
    needs: check-changes
    if: needs.check-changes.outputs.rewise_detected == 'true'
    uses: ./.github/workflows/build-app.yml
    with:
      vercel-project-id: ${{ needs.check-changes.outputs.project_id }}
    secrets: inherit
