name: Vercel Platform Preview Deployment
on:
  workflow_run:
    workflows: [ "Detect Changes for Apps" ]
    types: [ completed ]
    branches-ignore: [ production ]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      web_detected: ${{ steps.check-web.outputs.web_detected }}
    steps:
    - name: Download apps-to-build artifact
      uses: actions/download-artifact@v4
      with:
        name: apps-to-build
        path: ./
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Check if web should be built
      id: check-web
      run: |
        if [ -f "apps-to-build.txt" ]; then
          if grep -q "web" "apps-to-build.txt"; then
            echo "web_detected=true" >> $GITHUB_OUTPUT
            echo "✅ Web changes detected, proceeding with build"
          else
            echo "web_detected=false" >> $GITHUB_OUTPUT
            echo "❌ No Web changes detected, skipping build"
          fi
        else
          echo "web_detected=false" >> $GITHUB_OUTPUT
          echo "❌ apps-to-build.txt not found, skipping build"
        fi

  deploy-web:
    needs: check-changes
    if: needs.check-changes.outputs.web_detected == 'true'
    uses: ./.github/workflows/build-app.yml
    with:
      vercel-project-id: ${{ secrets.VERCEL_WEB_PROJECT_ID }}
    secrets: inherit
