name: Vercel Tumeet Preview Deployment
on:
  workflow_run:
    workflows: [ "Detect Changes for Apps" ]
    types: [ completed ]
    branches-ignore: [ production ]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      tumeet_detected: ${{ steps.check-tumeet.outputs.tumeet_detected }}
    steps:
    - name: Download apps-to-build artifact
      uses: actions/download-artifact@v4
      with:
        name: apps-to-build
        path: ./
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Check if tumeet should be built
      id: check-tumeet
      run: |
        if [ -f "apps-to-build.txt" ]; then
          if grep -q "tumeet" "apps-to-build.txt"; then
            echo "tumeet_detected=true" >> $GITHUB_OUTPUT
            echo "✅ Tumeet changes detected, proceeding with build"
          else
            echo "tumeet_detected=false" >> $GITHUB_OUTPUT
            echo "❌ No Tumeet changes detected, skipping build"
          fi
        else
          echo "tumeet_detected=false" >> $GITHUB_OUTPUT
          echo "❌ apps-to-build.txt not found, skipping build"
        fi

  deploy-tumeet:
    needs: check-changes
    if: needs.check-changes.outputs.tumeet_detected == 'true'
    uses: ./.github/workflows/build-app.yml
    with:
      vercel-project-id: ${{ secrets.VERCEL_TUMEET_PROJECT_ID }}
    secrets: inherit
