name: Vercel Tumeet Preview Deployment
on:
  workflow_run:
    workflows: [ "Detect Changes for Apps" ]
    types: [ completed ]
    branches-ignore: [ production ]

jobs:
  deploy-tumeet:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Download apps-to-build artifact
      uses: actions/download-artifact@v4
      with:
        name: apps-to-build
        path: ./
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Check if tumeet should be built
      id: check-tumeet
      run: |
        if [ -f "apps-to-build.txt" ]; then
          if grep -q "tumeet" "apps-to-build.txt"; then
            echo "tumeet_detected=true" >> $GITHUB_OUTPUT
            echo "✅ Tumeet changes detected, proceeding with build"
          else
            echo "tumeet_detected=false" >> $GITHUB_OUTPUT
            echo "❌ No Tumeet changes detected, skipping build"
          fi
        else
          echo "tumeet_detected=false" >> $GITHUB_OUTPUT
          echo "❌ apps-to-build.txt not found, skipping build"
        fi

    - name: Build and Deploy Tumeet
      if: steps.check-tumeet.outputs.tumeet_detected == 'true'
      uses: ./.github/workflows/build-app.yml
      with:
        app: tumeet
        app-path: apps/tumeet
        build-command: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        vercel-project-id: ${{ secrets.VERCEL_TUMEET_PROJECT_ID }}
      secrets:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
